[tool.poetry]
name = "fastapi-mini-project"
version = "0.1.0"
description = ""
authors = ["kihoon <nike6736@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.119.1"
uvicorn = "^0.38.0"
pydantic-settings = "^2.11.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

